server:
  port: 8080
spring:
  application:
    name: person-management
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/personmanagement
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      generate-ddl: true
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    sql-migration-prefix: v